# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_checked_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_save_cb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_cb.setGeometry(QtCore.QRect(150, 220, 161, 61))
        self.btn_save_cb.setObjectName("btn_save_cb")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(370, 50, 181, 131))
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 40, 161, 161))
        self.widget.setObjectName("widget")
        self.vlayout_hobby = QtWidgets.QVBoxLayout(self.widget)
        self.vlayout_hobby.setContentsMargins(0, 0, 0, 0)
        self.vlayout_hobby.setObjectName("vlayout_hobby")
        self.cb_cinema = QtWidgets.QCheckBox(self.widget)
        self.cb_cinema.setObjectName("cb_cinema")
        self.vlayout_hobby.addWidget(self.cb_cinema)
        self.cb_read_book = QtWidgets.QCheckBox(self.widget)
        self.cb_read_book.setObjectName("cb_read_book")
        self.vlayout_hobby.addWidget(self.cb_read_book)
        self.cb_sport = QtWidgets.QCheckBox(self.widget)
        self.cb_sport.setObjectName("cb_sport")
        self.vlayout_hobby.addWidget(self.cb_sport)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_save_cb.setText(_translate("MainWindow", "Save choosen"))
        self.cb_cinema.setText(_translate("MainWindow", "Cinema"))
        self.cb_read_book.setText(_translate("MainWindow", "Read a book"))
        self.cb_sport.setText(_translate("MainWindow", "Sport"))
