# Generated by Django 4.0.3 on 2022-03-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_image_itself'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_itself',
        ),
        migrations.AddField(
            model_name='movie',
            name='caption',
            field=models.CharField(default='1.jpeg', max_length=50, verbose_name='Film Resmi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
